"""init db

Revision ID: 253442868274
Revises: 26ee63b644d4
Create Date: 2024-11-16 23:29:41.462941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253442868274'
down_revision = '26ee63b644d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machines_machine_id'), ['machine_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_machines_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machines_user_id'))
        batch_op.drop_index(batch_op.f('ix_machines_machine_id'))

    op.drop_table('machines')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
